### ISSUE TITLE
Avoid repeatedly printing debug logs when tracing relation is yet to be formed

### ISSUE THREAD

**Issue by shayancanonical** [canonical/tempo-k8s-operator#163]
### Bug Description

The following are log statements in the tracing libs, which are printed for every invoked event on the charm side:

```
unit-mysql-k8s-0: 14:52:00 DEBUG unit.mysql-k8s/0.juju-log no relation on 'tracing': tracing not ready
```

The result is that the logs of the charm using these tracing charm libs (database charms) get mixed with the logs of the tracing charm libs, making it really difficult to read the logs that belong to the charm that would be related to tempo.``

### To Reproduce

1. juju deploy -n 1 mysql-k8s --channel 8.0/edge
2. juju model-config logging-config="unit.mysql-k8s/0=DEBUG"
3. juju debug-log

### Environment

juju version: 3.5.3-genericlinux-amd64  
microk8s version: MicroK8s v1.31.0 revision 7114
controller version: 3.5.3
mysql-k8s revision: 184

### Relevant log output

```shell
unit-mysql-k8s-0: 14:07:55 DEBUG unit.mysql-k8s/0.juju-log tracing:3: ops 2.15.0 up and running.
unit-mysql-k8s-0: 14:07:55 DEBUG unit.mysql-k8s/0.juju-log tracing:3: no relation on 'tracing': tracing not ready
unit-mysql-k8s-0: 14:07:55 DEBUG unit.mysql-k8s/0.juju-log tracing:3: Emitting Juju event tracing_relation_broken.
unit-mysql-k8s-0: 14:07:55 WARNING unit.mysql-k8s/0.juju-log tracing:3: 'app' expected but not received.
unit-mysql-k8s-0: 14:08:00 DEBUG unit.mysql-k8s/0.juju-log ops 2.15.0 up and running.
unit-mysql-k8s-0: 14:08:01 DEBUG unit.mysql-k8s/0.juju-log no relation on 'tracing': tracing not ready
unit-mysql-k8s-0: 14:08:01 DEBUG unit.mysql-k8s/0.juju-log Emitting Juju event rotate_mysql_logs.
```

**Comment by ca-scribner** [comment]
Hey @shayancanonical.  You're completely right, but it works how we intend and we don't have a great alternative :)

The intent is that the tracing lib tells you "I'm connected to X" or "I'm not connected", based on whether the relation is established.  Our thinking was that, since it is in the `DEBUG` logs, being noisy is an acceptable cost.  But I get where you're coming from that, since it gets lumped in with other logs, it can make reading the logs harder.  

We don't want to disable the messaging entirely, and we don't have a better alternative to what is implemented right now.  Do you have an alternate suggestion?  We're closing for now with the intent that we don't change this, but if you have an alternative or its a really big issue please reopen :)

**Comment by shayancanonical** [comment]
@ca-scribner 

charm tracing is, as i understand, a way to instrument the charm code which is a rarity in production deployments (or more often not used than used in production). however, i also understand the value of the logs during the development of the library

suggestion: would it be possible to distinguish the `loggers` in the [tracing charm lib code](https://github.com/canonical/mysql-operator/blob/main/lib/charms/tempo_k8s/v2/tracing.py#L840) like the [charm tracing library does](https://github.com/canonical/mysql-operator/blob/main/lib/charms/tempo_k8s/v1/charm_tracing.py#L277-L281)?

another suggestion: would it be possible to reword the logs to something like `skipping charm trace as no 'tracing' integration available`?
